services:
  api:
    build: ./api-backend
    container_name: api-backend
    networks:
      - modsec-net

  modsec:
    image: owasp/modsecurity-crs:nginx
    container_name: modsec-waf
    ports:
      - "8080:8080"
    environment:
      - BACKEND=http://api:8000
      - PARANOIA=3
      - ANOMALY_INBOUND=5
      - ANOMALY_OUTBOUND=4
      - BLOCKING_PARANOIA=1
      - MODSEC_RULE_ENGINE=On # DetectionOnly  # it'll log the violation but still pass the request through
      - MODSEC_AUDIT_ENGINE=RelevantOnly
      - MODSEC_AUDIT_LOG_FORMAT=JSON
      - MODSEC_AUDIT_LOG=/var/log/modsecurity/audit/audit.log
      - MODSEC_REQ_BODY_ACCESS=On
      - MODSEC_RESP_BODY_ACCESS=Off
    volumes:
      - ./modsec-logs:/var/log/modsecurity/audit
      - ./custom-rules/modsecurity-override.conf:/etc/modsecurity.d/owasp-crs/rules/REQUEST-900-METHOD-POLICY.conf
    depends_on:
      - api
    networks:
      - modsec-net

networks:
  modsec-net:
    driver: bridge