SecAction "id:900100,phase:1,pass,nolog,setvar:'tx.allowed_methods=GET HEAD POST OPTIONS PUT PATCH DELETE'"

SecRule REQUEST_URI "@detectSQLi" \
    "id:900201,\
    phase:2,\
    block,\
    capture,\
    t:none,t:urlDecodeUni,\
    msg:'SQL Injection Attack Detected in URI',\
    logdata:'Matched Data: %{TX.0} found within %{MATCHED_VAR_NAME}: %{MATCHED_VAR}',\
    tag:'application-multi',\
    tag:'language-multi',\
    tag:'platform-multi',\
    tag:'attack-sqli',\
    tag:'OWASP_CRS',\
    tag:'paranoia-level/1',\
    ver:'OWASP_CRS/3.3.10',\
    severity:'CRITICAL',\
    setvar:'tx.anomaly_score_pl1=+%{tx.critical_anomaly_score}',\
    setvar:'tx.sql_injection_score=+%{tx.critical_anomaly_score}'"

SecRule REQUEST_METHOD "@rx ^(DELETE|GET|HEAD)$" \
    "id:900202,\
    phase:2,\
    chain,\
    deny,status:403,\
    t:none,\
    msg:'Request body sent on %{REQUEST_METHOD} method',\
    logdata:'Content-Length: %{REQUEST_HEADERS.Content-Length}',\
    tag:'application-multi',\
    tag:'language-multi',\
    tag:'platform-multi',\
    tag:'attack-generic',\
    tag:'OWASP_CRS',\
    ver:'OWASP_CRS/3.3.10',\
    severity:'WARNING'"
    SecRule REQUEST_BODY "@rx ." \
        "t:none"
